server:
  port: 10010
spring:
  application:
    name: springCloud-zuul
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true
    fetch-registry: true
zuul:
  prefix: /api # 路由路径前缀
  routes:
      item-service: /item/**