server:
  port: 8001
spring:
  application:
    name: springCloud-eureka-8001
eureka:
  instance:
    hostname: eureka1
  client:
    fetch-registry: false # 拉取eureka服务信息
    register-with-eureka: false # 把自己注册到eureka服务列表
    service-url:
      defaultZone: http://eureka2:8002/eureka,http://eureka3:8003/eureka
#  server:
#    enable-self-preservation: false   # 关闭自我保护
#    eviction-interval-timer-in-ms: 5000
# 每隔5秒钟，进行一次服务列表的清理
#### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
#### 配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题